### ISSUE TITLE
Is the license "All rights reserved" or "BSD 3"?

### ISSUE THREAD

**Issue by ghost** [andresperezlopez/masp#1]
The file LICENCE.md file is a description of the BSD 3-Clause License, preceded with the name of authors, then "All rights reserved".

The python files also contains a copyright notice:
# Copyright (c) 2019, Eurecat / UPF
# All rights reserved.
Followed by the text of the BSD 3 license.

If the license is BSD 3, adding "All rights reserved" is a bit confusing.

**Comment by andresperezEUT** [comment]
Hi.
You are right. License for all files is BSD 3-Clause. 
I'll remove the confusing parts.
Thank you.
